//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Constantino.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrador
    {
        public int AdministradorId { get; set; }
        public string Codigo { get; set; }
        public string Password { get; set; }
        public string Estado { get; set; }
        public string Rol { get; set; }
    }
}
