//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Constantino.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificacion
    {
        public int CertificacionId { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> FechaCertificacion { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<System.DateTime> FechaActual { get; set; }
        public Nullable<int> DiasVencimiento { get; set; }
        public string EstadoCertificacion { get; set; }
        public int TrabajadorId { get; set; }
        public string Estado { get; set; }
        public string NombreArchivo { get; set; }
        public string RutaArchivo { get; set; }
        public Nullable<int> InstitucionId { get; set; }
        public string OtraInstitucion { get; set; }
    
        public virtual Institucion Institucion { get; set; }
        public virtual Trabajador Trabajador { get; set; }
    }
}
