//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Constantino.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento
    {
        public int DocumentoId { get; set; }
        public int TrabajadorId { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Ruta { get; set; }
        public string Estado { get; set; }
        public string Nombre { get; set; }
    
        public virtual Trabajador Trabajador { get; set; }
    }
}
