//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Constantino.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificacion
    {
        public int NotificacionId { get; set; }
        public string Titulo { get; set; }
        public string Mensaje { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Estado { get; set; }
        public Nullable<bool> EsCorreo { get; set; }
        public Nullable<bool> EsNotificacion { get; set; }
    }
}
