//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Constantino.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProyectoSector
    {
        public int ProyectoSubSectorId { get; set; }
        public int ProyectoId { get; set; }
        public int SubSectorId { get; set; }
        public string Estado { get; set; }
    
        public virtual Proyecto Proyecto { get; set; }
        public virtual SubSector SubSector { get; set; }
    }
}
