//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Constantino.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trabajador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trabajador()
        {
            this.Certificacion = new HashSet<Certificacion>();
            this.Colegiatura = new HashSet<Colegiatura>();
            this.Documento = new HashSet<Documento>();
            this.Estudios = new HashSet<Estudios>();
            this.Experiencia = new HashSet<Experiencia>();
            this.IdiomaTrabajador = new HashSet<IdiomaTrabajador>();
            this.PostGrado = new HashSet<PostGrado>();
        }
    
        public int TrabajadorId { get; set; }
        public string Codigo { get; set; }
        public string Nombres { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string NroDocumento { get; set; }
        public string Estado { get; set; }
        public string Direccion { get; set; }
        public string Referencia { get; set; }
        public Nullable<int> DistritoId { get; set; }
        public string Celular { get; set; }
        public string Telefono { get; set; }
        public string CorreoElectronico { get; set; }
        public Nullable<int> TipoDocumentoId { get; set; }
        public string Password { get; set; }
        public string FolderGuid { get; set; }
        public string codigo_empleado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Certificacion> Certificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Colegiatura> Colegiatura { get; set; }
        public virtual Distrito Distrito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documento> Documento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estudios> Estudios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Experiencia> Experiencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdiomaTrabajador> IdiomaTrabajador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostGrado> PostGrado { get; set; }
        public virtual TipoDocumento TipoDocumento { get; set; }
    }
}
