//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Constantino.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Postulacion = new HashSet<Postulacion>();
        }
    
        public int UsuarioId { get; set; }
        public string CorreoElectronico { get; set; }
        public string Password { get; set; }
        public string Nombres { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string NombreCompleto { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string DNI { get; set; }
        public string NumeroContacto1 { get; set; }
        public string NumeroContacto2 { get; set; }
        public bool EsTrabajador { get; set; }
        public bool TieneEstudios { get; set; }
        public int EspecialidadId { get; set; }
        public int DistritoId { get; set; }
        public string Estado { get; set; }
        public string DeviceToken { get; set; }
    
        public virtual Distrito Distrito { get; set; }
        public virtual Especialidad Especialidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Postulacion> Postulacion { get; set; }
    }
}
